// Writes art/cards/redo.json (#21): the 60 candidates (15 X cards x 4), prompt / model / seed / steps.   node art/cards/redo-prompts.mjs
// Seed = 21000 + card number * 10 + candidate number. Candidates 1-4 are Qwen Image 2.1 (25 steps); for the real_tech X cards (24, 67, 72) candidate 4 is Z-Image Turbo (20 steps).
// Ten cards keep the prompts.json prompt word for word; five (REWRITE) get a rewritten Scene that cures the known defect without changing who / where / when.
import fs from 'node:fs'; import path from 'node:path';
import { load, dir } from './pickdata.mjs';
export const X = [11, 12, 13, 16, 17, 24, 33, 36, 37, 39, 53, 64, 65, 67, 72];
export const REWRITE = {
  sino_soviet_treaty: 'The Kremlin in Moscow on the night of 14 August 1945, the moment after the signing: Chinese Foreign Minister Wang Shijie in a dark Western suit and Soviet Foreign Minister Molotov stand shaking hands across a polished table, a closed dark-red leather portfolio lying shut in front of them with two fountain pens beside it, the whole tabletop otherwise bare, Joseph Stalin, grey-haired with a heavy grey-black moustache in a plain pale tunic and holding his pipe, stands smiling behind them, T. V. Soong, a lean man in round glasses and a dark long gown, beside him, gilded walls, crystal chandeliers and red velvet curtains, press photographers with flashbulbs, low-angle close-up on the clasped hands and the closed portfolio. Moscow, August 1945, formal suits and uniforms, not a single sheet of paper or page of writing visible anywhere in the picture.',
  marshall_mission: "A sunny garden terrace with a plum tree in a villa in Nanjing, a wide shot of exactly three men standing side by side in a row, full figures, each clearly different: in the centre General George Marshall, tall and straight with silver-grey hair and a lined, stern face, in a US Army general's uniform, his arms stretched out wide to both sides with one open hand toward each of the others; on his left Chiang Kai-shek, a lean upright man with a close-shaved bald head and a lean long face, in a plain khaki tunic with no decorations; on his right Zhou Enlai, a slim man with a narrow face, thick straight black eyebrows and short neat dark hair, in a grey Zhongshan suit; a garden table behind them with a rolled map, warm afternoon light, the three of them filling the foreground and nobody else in front of them. Nanjing, 1946, no readable documents, no signboards.",
  league_banned: "A plain black lacquered double door set in a bare grey brick wall of a lane house in a Shanghai alley at dusk, the wall and door completely blank and unmarked: Nationalist policemen and plain-clothes agents in dark long gowns and fedoras carry out boxes of papers and a mimeograph machine while an elderly man with a white goatee, round spectacles and a long grey gown, the Democratic League's chairman Zhang Lan, stands upright in the doorway with a hand on his cane, a black sedan with its headlamps on, a policeman pulling the black double doors shut with a heavy lock, the only light a single street lamp and the sedan's headlamps, low angle. Shanghai, October 1947, 1940s police uniforms, no readable papers, no door plates, no plaques, no signboards, no lanterns, no posters, nothing hanging on the wall or door.",
  new_consultative_conference: 'A grand hall in Beiping lit in warm red for the opening of the Political Consultative Conference: Mao Zedong, a stocky man with a broad round face, a high forehead and thick black hair combed straight back, in a grey tunic, stands at a podium with his hand raised, hundreds of delegates in rows before him, among them a Tibetan lama in maroon robes, a Mongol in a long robe, a Hui man in a white cap, women in cadre uniforms, scholars in suits and long gowns, the whole stage and wall hung with plain deep-red velvet curtains and rows of round red paper lanterns, low-angle view. Beiping, September 1949, no flags of any kind, no banners, no emblems, no stars, no signboards, no soldiers.',
  stalins_advice: "A plain village house at Xibaipo in snow: four Chinese leaders in plain padded grey-blue cotton jackets, Mao Zedong, a stocky round-faced man with thick black hair combed back, Liu Shaoqi, Zhou Enlai and Zhu De, sit on one side of a rough wooden table with a map and tea cups, facing the Soviet visitor Anastas Mikoyan on the other side, plainly a European: a stout, pale-skinned man with a heavy black moustache, a large nose, thick dark eyebrows and receding dark hair, in a dark Western suit and tie with a heavy long dark overcoat with a fur collar, a fur hat on the table beside him, a coal stove glowing in the corner, small paned windows with snow outside, heavy cigarette smoke in a lamp's glow. Xibaipo, Hebei, early 1949, no readable writing on the map.",
};
const NOTEXT = ' No text, no characters, no seals, no writing. Full-bleed';
const cards = load(), P = JSON.parse(fs.readFileSync(path.join(dir, 'prompts.json'), 'utf8')), out = [];
for (const n of X) {
  const c = cards.find((k) => k.num === String(n)); const e = P.find((p) => p.key === c.key);
  const i = e.prompt.indexOf(' Scene: '), j = e.prompt.indexOf(NOTEXT);
  if (i < 0 || j < 0) throw new Error('prompt shape ' + c.key);
  const prompt = REWRITE[c.key] ? e.prompt.slice(0, i + 8) + REWRITE[c.key] + e.prompt.slice(j) : e.prompt;
  for (let k = 1; k <= 4; k++) {
    const z = e.style === 'real_tech' && k === 4;
    out.push({ key: c.key, c: k, model: z ? 'zimage' : 'qwen', seed: 21000 + n * 10 + k, steps: z ? 20 : 25, prompt });
  }
}
if (process.argv[1] && process.argv[1].endsWith('redo-prompts.mjs')) { fs.writeFileSync(path.join(dir, 'redo.json'), JSON.stringify(out, null, 2) + '\n'); console.log('redo.json', out.length); }
